### ISSUE TITLE
java.lang.ClassCastException when deserializing from Salat in context of akka runtime.

### ISSUE THREAD

**Issue by martende** [salat/salat#162] opened 2016-03-22 14:53 UTC
I have a rather strange behavior for one salat object that is described like 

```
case class InnerDomain(domain:String,expired:DateTime,ip:Option[String], .... )

class InnerDomainDAO(conn:MongoClient) extends SalatDAO[InnerDomain, ObjectId](collection= conn("testdb")("innerdomains")) 

```

val dao = new InnerDomainDAO(dbconnection)
```

// WORKS
val items = dao.find(DBObject("isActive" -> true)).toList
// WORKS - and prints right deserealised MONGO object 
 45         println(items)
// Throws excaption ( below)
 46         for ( item <- items) {
 47           val url = "http://" + item.domain
 48           log.info(s"Test $url")
 49         }

java.lang.ClassCastException: common.InnerDomain cannot be cast to common.InnerDomain
	at actors.DomainChecker$anonfun$1$anonfun$apply$2.apply(DomainChecker.scala:46) ~[classes/:na]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.7.jar:na]
	at actors.DomainChecker$anonfun$1.apply(DomainChecker.scala:46) ~[classes/:na]
	at actors.DomainChecker$anonfun$1.apply(DomainChecker.scala:42) ~[classes/:na]


```

**Comment by noahlz** [comment] 2016-03-22 17:41
At first glance, that looks like some kind of odd class loader issue, not specific to Salat.

See
http://stackoverflow.com/a/2615014/7507
http://stackoverflow.com/q/5483420/7507

Does this happen when you run your code in a simple Scala command-line application? You can adapt my salat-example project to hack something together quickly:
https://github.com/noahlz/salat-examples

**Comment by martende** [comment] 2016-03-22 17:54
I think also that it can be a classloader issue . But why println(items) works - this i can not understand. 
Btw. I am using akka environment for this code .

**Comment by noahlz** [comment] 2016-03-22 18:53
In order to provide feedback on this issue, you'll need to provide a trivial example that reproduces the issue. I recommend using my salat-examples repo as a starting point.

**Comment by noahlz** [comment] 2016-05-26 13:28
Closing issue - please re-open with example code.

**Closed** 2016-05-26 13:27 UTC
